services:
  web:
    image: arpanoj/a3-car-price:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-st127304-a3.rule=Host(`web-st127304-a3.ml.brain.cs.ait.ac.th`)"
      - "traefik.http.routers.web-st127304-a3.entrypoints=websecure"          
      - "traefik.http.routers.web-st127304-a3.tls=true"
      - "traefik.http.routers.web-st127304-a3.tls.certresolver=letsencrypt"   
      - "traefik.http.services.web-st127304-a3.loadbalancer.server.port=8050"
    networks:
      - traefik

networks:
  traefik:
    name: web                                               
    external: true
