name: CI-CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r app/requirements.txt pytest

      - name: Run unit tests
        run: pytest -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: arpanoj
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: arpanoj/a3-car-price:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull and restart on ml-brain
        uses: appleboy/ssh-action@v1
        with:
          host: ml.brain.cs.ait.ac.th
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          proxy_host: ${{ secrets.JUMP_HOST }}
          proxy_username: ${{ secrets.SSH_USERNAME }}
          proxy_password: ${{ secrets.JUMP_PASSWORD }}

          script: |
            cd ~/st127304-a3
            docker compose pull
            docker compose up -d
